backend:
  name: github
  repo: username/repository-name  # Update this with actual repo
  branch: main
  base_url: https://decap-proxy-projectname.username.workers.dev  # Update this with actual worker URL
  auth_endpoint: /auth

local_backend: false
site_url: "https://your-domain.com"  # Update this with actual domain
display_url: "https://your-domain.com"  # Update this with actual domain
media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/settings/general.yml"
        label: "General Settings"
        name: "general"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Site Logo", name: "site_logo", widget: "image", required: false}
          - {label: "Contact Email", name: "contact_email", widget: "string"}
          - {label: "Social Media", name: "social", widget: "object", fields: [
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "GitHub", name: "github", widget: "string", required: false}
            ]}

  - name: "navigation"
    label: "Navigation"
    files:
      - file: "content/navigation/main.yml"
        label: "Main Navigation"
        name: "main"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "External", name: "external", widget: "boolean", default: false} 